
-- 카테고리 조회
SELECT C1.NAME AS MAIN_NAME, C2.NO AS NO, C2.NAME AS SUB_NAME
FROM TBL_CATEGORY C1
    RIGHT JOIN TBL_CATEGORY C2 ON C2.SUB_NO = C1.NO;


-- 프로젝트 조회 상태 별
SELECT TP.NO AS NO,
       TP.TITLE AS TITLE,
       TP.CONTENT AS CONTENT,
       TP.REGIST_DATE AS REGIST_DATE,
       TP.CURRENT_AMOUNT AS CURRENT_AMOUNT,
       TP.TARGET_AMOUNT AS TARGET_AMOUNT,
       TPP.CONTENT AS STATUS_CONTENT,
       TPP.STATUS AS STATUS
FROM TBL_PRJ TP
         JOIN TBL_PRJ_PROGRESS TPP ON TPP.REF_PRJ_NO = TP.NO;
WHERE TPP.STATUS = 'CANCEL';

-- 프로젝트 별 판매자 정보

SELECT PRJ.NO, PRJ.TITLE, PRJ.CONTENT, PRJ.REGIST_DATE,
       PRJ.START_DATE,PRJ.END_DATE, PRJ.TARGET_AMOUNT,PRJ.CURRENT_AMOUNT, PRJ.VIEWS,
       TM.ID, TM.NAME, TM.NICKNAME,
       TM.STATUS, TSR.ACCOUNT_NO, TSR.BANK, TSR.CALL_NUMBER,
       TSR.REGIST_NO, TSR.NAME, TSR.ADDRESS, C3.MAIN_NAME, C3.NO, SUB_NAME
  FROM TBL_PRJ PRJ
  JOIN TBL_MEMBER TM on PRJ.REF_MEMBER_NO = TM.NO
  JOIN TBL_SELLER_ROLE TSR on TM.NO = TSR.REF_MEMBER_NO
  JOIN (SELECT C1.NAME AS MAIN_NAME, C2.NO AS NO, C2.NAME AS SUB_NAME
          FROM TBL_CATEGORY C1
         RIGHT JOIN TBL_CATEGORY C2 ON C2.SUB_NO = C1.NO) C3 ON C3.NO = PRJ.REF_CATEGORY_NO;

--프로젝트 별 상품리스트 조회
SELECT
    PRJ.TITLE AS TITLE,
    PRJ.REGIST_DATE AS REGIST_DATE,
    TP.NAME AS NAME,
    TP.INTRODUCTION AS INTRODUCTION,
    TP.MAX_QUANTITY AS MAX_QUANTITY,
    TP.PRICE AS PRICE,
    TP.STATUS AS STATUS,
    TP.PRODUCT_SIZE AS PRODUCT_SIZE
FROM TBL_PRJ_PRODUCT_LIST TPPL
         JOIN TBL_PRODUCT TP ON TP.NO = TPPL.REF_PRODUCT_NO
         JOIN TBL_PRJ PRJ ON PRJ.NO = TPPL.REF_PRJ_NO;


-- 프로젝트 등록 상품리스트 조회
SELECT TPRL.NO,
       TP.NO,
       TP.NAME,
       TP.INTRODUCTION,
       TP.PRICE,
       TP.MAX_QUANTITY,
       TP.STATUS,
       TP.PRODUCT_SIZE
  FROM TBL_PRJ_PRODUCT_LIST TPRL
  JOIN TBL_PRODUCT TP ON TPRL.REF_PRODUCT_NO = TP.NO
 WHERE TPRL.REF_PRJ_NO = 0;

-- 프로젝트 상태 조회

SELECT PRJ.NO, PRJ.TITLE, PRJ.CONTENT,
       PRJ.REGIST_DATE, PRJ.TARGET_AMOUNT, PRJ.CURRENT_AMOUNT,
       PRJ.REF_MEMBER_NO, TPP2.REGIST_DATE, TPP2.STATUS,
       TPP2.CONTENT, TM.NAME, TM.PHONE,
       TM.ID, TM.STATUS
  FROM TBL_PRJ PRJ
  JOIN (SELECT *
          FROM TBL_PRJ_PROGRESS
         WHERE NO = (SELECT MAX(NO)
                       FROM TBL_PRJ_PROGRESS
                      WHERE REF_PRJ_NO = 0)
) TPP2 ON TPP2.REF_PRJ_NO = PRJ.NO
  JOIN TBL_MEMBER TM ON TM.NO = PRJ.REF_MEMBER_NO;


-- 프로젝트 FAQ 조회
SELECT *
  FROM TBL_PRJ PRJ
  JOIN TBL_PRJ_FAQ TPF ON PRJ.NO = TPF.REF_PRJ_NO;

SELECT TPF.TITLE, TPF.CONTENT, TPF.REGIST_DATE
FROM TBL_PRJ_FAQ TPF
WHERE REF_PRJ_NO = 0
ORDER BY REGIST_DATE DESC;

-- 프로젝트 정보 조회
SELECT PRJ.NO, PRJ.TITLE, PRJ.CONTENT,
       PRJ.REGIST_DATE, PRJ.START_DATE, PRJ.END_DATE,
       PRJ.TARGET_AMOUNT, PRJ.CURRENT_AMOUNT, PRJ.VIEWS,
       PRJ.REF_MEMBER_NO, PRJ.REF_CATEGORY_NO
  FROM TBL_PRJ PRJ
 WHERE NO = 0;

-- 프로젝트 별 파일 목록 조회
SELECT PRJ.NO, PRJ.TITLE, PRJ.CONTENT, PRJ.REGIST_DATE,
       PRJ.START_DATE, PRJ.END_DATE, PRJ.TARGET_AMOUNT, PRJ.CURRENT_AMOUNT,
       PRJ.VIEWS, TPF.TYPE, TPF.ORIGIN_NAME, TPF.DELETE_YN, TPF.CHANGE_NAME,
       TPF.REGIST_DATE
  FROM TBL_PRJ PRJ
  LEFT JOIN TBL_PRJ_FILE TPF ON PRJ.NO = TPF.REF_PRJ_NO;


-- Q/A 리스트 조회
SELECT *
  FROM TBL_PRJ PRJ
 RIGHT JOIN TBL_PRJ_QNA TPQ ON TPQ.REF_PRJ_NO = PRJ.NO
  JOIN TBL_MEMBER TM1 ON TM1.NO = TPQ.REF_MEMBER_NO
  LEFT JOIN TBL_PRJ_QNA_ANSWER TPQA ON TPQA.PRJ_QNA_CODE = TPQ.NO
  LEFT JOIN TBL_MEMBER TM2 ON TM2.NO = TPQA.REF_MEMBER_NO
WHERE TPQA.NO IS NOT NULL; -- 답변 여부

-- Q/A no 조회
SELECT * FROM TBL_PRJ_QNA TPQ
                  JOIN TBL_MEMBER TM1 ON TM1.NO = TPQ.REF_MEMBER_NO
                  LEFT JOIN TBL_PRJ_QNA_ANSWER TPQA ON TPQA.PRJ_QNA_CODE = TPQ.NO
                  LEFT JOIN TBL_MEMBER TM2 ON TM2.NO = TPQA.REF_MEMBER_NO
WHERE TPQ.NO = '0';


-- 프로젝트 아이템 조회용 카테고리 필터

SELECT NO,
    PRJ.TITLE,
    PRJ.CONTENT,
    PRJ.START_DATE,
    PRJ.END_DATE,
    PRJ.TARGET_AMOUNT,
    PRJ.CURRENT_AMOUNT,
    PRJ.VIEWS,
    PRJ.REF_CATEGORY_NO
FROM TBL_PRJ PRJ
WHERE PRJ.REF_CATEGORY_NO = (SELECT TC.NO
    FROM TBL_CATEGORY TC
    WHERE TC.NAME = '후드 티셔츠'
    );

