CREATE OR REPLACE TRIGGER  TGR_CURRENT_AMOUNT
    AFTER
        INSERT ON TBL_PAYMENT
    FOR EACH ROW
BEGIN
    IF :NEW.STATUS = 'APPROVAL'
    THEN
UPDATE TBL_PRJ PRJ
SET PRJ.CURRENT_AMOUNT = PRJ.CURRENT_AMOUNT + :NEW.AMOUNT
WHERE PRJ.NO = (SELECT PRJ.NO FROM TBL_PAYMENT_HISTORY TPH
                                       JOIN TBL_SPONSORED_PRJ TSP ON TSP.NO  = TPH.REF_SPONSORED_PRJ_NO
                                       JOIN TBL_PRJ_PRODUCT_LIST TPPL  ON TPPL.NO = TSP.REF_PRJ_PRODUCT_LIST_NO
                                       JOIN TBL_PRJ TP ON TP.NO = TPPL.REF_PRJ_NO
                WHERE TPH.REF_PAYMENT_NO = :NEW.CODE );
end if;
    IF :NEW.STATUS = 'REFUND'
    THEN
UPDATE TBL_PRJ PRJ
SET PRJ.CURRENT_AMOUNT = PRJ.CURRENT_AMOUNT - :NEW.AMOUNT
WHERE PRJ.NO = (SELECT PRJ.NO FROM TBL_PAYMENT_HISTORY TPH
                                       JOIN TBL_SPONSORED_PRJ TSP ON TSP.NO  = TPH.REF_SPONSORED_PRJ_NO
                                       JOIN TBL_PRJ_PRODUCT_LIST TPPL  ON TPPL.NO = TSP.REF_PRJ_PRODUCT_LIST_NO
                                       JOIN TBL_PRJ TP ON TP.NO = TPPL.REF_PRJ_NO
                WHERE TPH.REF_PAYMENT_NO = :NEW.CODE );
end if;
END;