#server port
server:
  port: 8080

# oracle config
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@serverpath:1521:xe
    username: ID
    password: PASSWORD
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

# mybatis mappers config
mybatis:
  mapper-locations: mybatis/mapper/**/*.xml

# SavedFilePath
saveFileDirectoryPath: c:\files

# SavedFilePath
sellerGetFormFileDirectoryPath: C:/dev/SemiProject/OSMASbySpringBoot/src/main/resources/static/images/admin/getForm



