#server port
server:
  port: 8080

# oracle config
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@oracle.coffit.site:1521:xe
    username: C##OSMAS
    password: OSMAS
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

# mybatis mappers config
mybatis:
  mapper-locations: mybatis/mapper/**/*.xml

# SavedFilePath
#saveFileDirectoryPath: /Users/yuseungcheol/Desktop/project/himedia/project/OSMASbySpringBoot/src/main/resources/static/files
saveFileDirectoryPath: c:\files

# SavedFilePath
#sellerGetFormFileDirectoryPath: C:/dev/SemiProject/osmas/src/main/resources/static/images/admin/getForm
sellerGetFormFileDirectoryPath: C:/Rendifull/getForm



