#server port

server:
  port: 8080

# oracle config
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@oracle.coffit.site:1521:xe
    username: C##OSMAS
    password: OSMAS

# mybatis mappers config
mybatis:
  mapper-locations: mybatis/mapper/**/*.xml
