
-- DROP SEQUENCE

-- DROP SEQUENCE SEQ_TBL_PAYMENT_HISTORY_NO;
-- DROP SEQUENCE SEQ_TBL_REVIEW_NO;
-- DROP SEQUENCE SEQ_TBL_ROLE_LIST_NO;
-- DROP SEQUENCE SEQ_TBL_SELLER_ROLE_NO;
-- DROP SEQUENCE SEQ_TBL_PRJ_WISH_NO;
DROP SEQUENCE SEQ_TBL_ADDRESS_NO;
DROP SEQUENCE SEQ_TBL_ADMIN_BOARD_NO;
DROP SEQUENCE SEQ_TBL_ADMIN_BOARD_FILE_NO;
DROP SEQUENCE SEQ_TBL_ALERT_NO;
DROP SEQUENCE SEQ_TBL_CATEGORY_NO;
DROP SEQUENCE SEQ_TBL_DELIVERY_STATUS_NO;
DROP SEQUENCE SEQ_TBL_MEMBER_NO;
DROP SEQUENCE SEQ_TBL_MEMBER_ROLE_CODE;
DROP SEQUENCE SEQ_TBL_PAYMENT_CODE;
DROP SEQUENCE SEQ_TBL_PERMISSION_ROLE_NO;
DROP SEQUENCE SEQ_TBL_PRJ_NO;
DROP SEQUENCE SEQ_TBL_PRJ_FAQ_NO;
DROP SEQUENCE SEQ_TBL_PRJ_FILE_NO;
DROP SEQUENCE SEQ_TBL_PRJ_NEW_INFO_NO;
DROP SEQUENCE SEQ_TBL_PRJ_NEW_INFO_FILE_NO;
DROP SEQUENCE SEQ_TBL_PRJ_PRODUCT_LIST_NO;
DROP SEQUENCE SEQ_TBL_PRJ_PROGRESS_NO;
DROP SEQUENCE SEQ_TBL_PRJ_QNA_NO;
DROP SEQUENCE SEQ_TBL_PRJ_QNA_ANSWER_NO;
DROP SEQUENCE SEQ_TBL_PRODUCT_NO;
DROP SEQUENCE SEQ_TBL_SELLER_ROLE_FILE_NO;
DROP SEQUENCE SEQ_TBL_SELLER_ROLE_REQ_NO;
DROP SEQUENCE SEQ_TBL_SHIPPING_TRACK_INFO_NO;
DROP SEQUENCE SEQ_TBL_SPONSORED_PRJ_NO;
DROP SEQUENCE SEQ_TBL_SUGGEST_NO;
DROP SEQUENCE SEQ_TBL_TERMS_HISTORY_NO;
DROP SEQUENCE SEQ_TBL_TERMS_NO;

COMMIT;

-- CREATE SEQUENCE


-- CREATE SEQUENCE SEQ_TBL_PAYMENT_HISTORY_NO;
-- CREATE SEQUENCE SEQ_TBL_REVIEW_NO;
-- CREATE SEQUENCE SEQ_TBL_ROLE_LIST_NO;
-- CREATE SEQUENCE SEQ_TBL_SELLER_ROLE_NO;
-- CREATE SEQUENCE SEQ_TBL_PRJ_WISH_NO;
CREATE SEQUENCE SEQ_TBL_ADDRESS_NO;
CREATE SEQUENCE SEQ_TBL_ADMIN_BOARD_NO;
CREATE SEQUENCE SEQ_TBL_ADMIN_BOARD_FILE_NO;
CREATE SEQUENCE SEQ_TBL_ALERT_NO;
CREATE SEQUENCE SEQ_TBL_CATEGORY_NO;
CREATE SEQUENCE SEQ_TBL_DELIVERY_STATUS_NO;
CREATE SEQUENCE SEQ_TBL_MEMBER_NO;
CREATE SEQUENCE SEQ_TBL_MEMBER_ROLE_CODE;
CREATE SEQUENCE SEQ_TBL_PAYMENT_CODE;
CREATE SEQUENCE SEQ_TBL_PERMISSION_ROLE_NO;
CREATE SEQUENCE SEQ_TBL_PRJ_NO;
CREATE SEQUENCE SEQ_TBL_PRJ_FAQ_NO;
CREATE SEQUENCE SEQ_TBL_PRJ_FILE_NO;
CREATE SEQUENCE SEQ_TBL_PRJ_NEW_INFO_NO;
CREATE SEQUENCE SEQ_TBL_PRJ_NEW_INFO_FILE_NO;
CREATE SEQUENCE SEQ_TBL_PRJ_PRODUCT_LIST_NO;
CREATE SEQUENCE SEQ_TBL_PRJ_PROGRESS_NO;
CREATE SEQUENCE SEQ_TBL_PRJ_QNA_NO;
CREATE SEQUENCE SEQ_TBL_PRJ_QNA_ANSWER_NO;
CREATE SEQUENCE SEQ_TBL_PRODUCT_NO;
CREATE SEQUENCE SEQ_TBL_SELLER_ROLE_FILE_NO;
CREATE SEQUENCE SEQ_TBL_SELLER_ROLE_REQ_NO;
CREATE SEQUENCE SEQ_TBL_SHIPPING_TRACK_INFO_NO;
CREATE SEQUENCE SEQ_TBL_SPONSORED_PRJ_NO;
CREATE SEQUENCE SEQ_TBL_SUGGEST_NO;
CREATE SEQUENCE SEQ_TBL_TERMS_NO;
CREATE SEQUENCE SEQ_TBL_TERMS_HISTORY_NO;

COMMIT;

select  * from USER_SEQUENCES