
ALTER TABLE TBL_ADDRESS
DROP CONSTRAINT TBL_ADDRESS_MEMBER_NO_FK;
ALTER TABLE TBL_ADMIN_BOARD
DROP CONSTRAINT TBL_ADMIN_BOARD_MEMBER_NO_FK;
ALTER TABLE TBL_ADMIN_BOARD_FILE
DROP CONSTRAINT TBL_ADMIN_BOARD_FILE_ADMIN_BOARD_NO_FK;
ALTER TABLE TBL_ALERT
DROP CONSTRAINT TBL_ALERT_MEMBER_NO_FK
    DROP CONSTRAINT TBL_ALERT_SUGGEST_NO_FK;
ALTER TABLE TBL_DELIVERY_STATUS
DROP CONSTRAINT TBL_DELIVERY_STATUS_SHIPPING_TRACK_INFO_NO_FK;
ALTER TABLE TBL_PAYMENT_HISTORY
DROP CONSTRAINT TBL_PAYMENT_HISTORY_PAYMENT_NO_FK
    DROP CONSTRAINT TBL_PAYMENT_HISTORY_SPONSORED_PRJ_NO_FK;
ALTER TABLE TBL_PERMISSION_ROLE
DROP CONSTRAINT TBL_PERMISSION_ROLE_SELLER_ROLE_REQ_NO_FK;
ALTER TABLE TBL_PRJ
DROP CONSTRAINT TBL_PRJ_MEMBER_NO_FK
    DROP CONSTRAINT TBL_PRJ_CATEGORY_NO_FK;
ALTER TABLE TBL_PRJ_FAQ
DROP CONSTRAINT TBL_PRJ_FAQ_PRJ_NO_FK;
ALTER TABLE TBL_PRJ_FILE
DROP CONSTRAINT TBL_PRJ_FILE_PRJ_NO_FK;
ALTER TABLE TBL_PRJ_NEW_INFO
DROP CONSTRAINT TBL_PRJ_NEW_INFO_MEMBER_NO_FK
    DROP CONSTRAINT TBL_PRJ_NEW_INFO_PRJ_NO_FK;
ALTER TABLE TBL_PRJ_NEW_INFO_FILE
DROP CONSTRAINT TBL_PRJ_NEW_INFO_FILE_PRJ_NEW_INFO_NO_FK;
ALTER TABLE TBL_PRJ_PRODUCT_LIST
DROP CONSTRAINT TBL_PRJ_PRODUCT_LIST_PRJ_NO1_FK
    DROP CONSTRAINT TBL_PRJ_PRODUCT_LIST_PRODUCT_NO1_FK;
ALTER TABLE TBL_PRJ_PROGRESS
DROP CONSTRAINT TBL_PRJ_PROGRESS_PRJ_NO_FK;
ALTER TABLE TBL_PRJ_QNA
DROP CONSTRAINT TBL_PRJ_QNA_MEMBER_NO_FK
    DROP CONSTRAINT TBL_PRJ_QNA_PRJ_NO_FK;
ALTER TABLE TBL_PRJ_QNA_ANSWER
DROP CONSTRAINT TBL_PRJ_QNA_ANSWER_MEMBER_NO_FK
    DROP CONSTRAINT TBL_PRJ_QNA_ANSWER_PRJ_QNA_CODE_FK;
ALTER TABLE TBL_PRJ_WISH
DROP CONSTRAINT TBL_PRJ_WISH_MEMBER_NO_FK
    DROP CONSTRAINT TBL_PRJ_WISH_PRJ_NO_FK;
ALTER TABLE TBL_REVIEW
DROP CONSTRAINT TBL_REVIEW_MEMBER_NO_FK
    DROP CONSTRAINT TBL_REVIEW_DELIVERY_STATUS_CODE_FK;
ALTER TABLE TBL_ROLE_LIST
DROP CONSTRAINT TBL_ROLE_LIST_MEMBER_NO_FK
    DROP CONSTRAINT TBL_ROLE_LIST_MEMBER_ROLE_CODE_FK;
ALTER TABLE TBL_SELLER_ROLE
DROP CONSTRAINT TBL_SELLER_ROLE_MEMBER_NO_FK;
ALTER TABLE TBL_SELLER_ROLE_FILE
DROP CONSTRAINT TBL_SELLER_ROLE_FILE_MEMBER_NO_FK;
ALTER TABLE TBL_SELLER_ROLE_REQ
DROP CONSTRAINT TBL_SELLER_ROLE_REQ_MEMBER_NO_FK;
ALTER TABLE TBL_SHIPPING_TRACK_INFO
DROP CONSTRAINT TBL_SHIPPING_TRACK_INFO_PAYMENT_NO_FK
    DROP CONSTRAINT TBL_SHIPPING_TRACK_INFO_MEMBER_NO_FK;
ALTER TABLE TBL_SPONSORED_PRJ
DROP CONSTRAINT TBL_SPONSORED_PRJ_PRJ_PRODUCT_LIST_NO_FK
    DROP CONSTRAINT TBL_SPONSORED_PRJ_MEMBER_NO_FK;
ALTER TABLE TBL_SUGGEST
DROP CONSTRAINT TBL_SUGGEST_CATEGORY_NO_FK
    DROP CONSTRAINT TBL_SUGGEST_MEMBER_NO_FK;
ALTER TABLE TBL_TERMS_HISTORY
DROP CONSTRAINT TBL_TERMS_HISTORY_TERMS_NO_FK;

COMMIT;

ALTER TABLE TBL_ADDRESS
    ADD CONSTRAINT TBL_ADDRESS_MEMBER_NO_FK FOREIGN KEY (REF_MEMBER_NO) REFERENCES TBL_MEMBER (NO);
ALTER TABLE TBL_ADMIN_BOARD
    ADD CONSTRAINT TBL_ADMIN_BOARD_MEMBER_NO_FK FOREIGN KEY (REF_MEMBER_NO) REFERENCES TBL_MEMBER (NO);
ALTER TABLE TBL_ADMIN_BOARD_FILE
    ADD CONSTRAINT TBL_ADMIN_BOARD_FILE_ADMIN_BOARD_NO_FK FOREIGN KEY (REF_ADMIN_BOARD_NO) REFERENCES TBL_ADMIN_BOARD (NO);
ALTER TABLE TBL_ALERT
    ADD CONSTRAINT TBL_ALERT_MEMBER_NO_FK FOREIGN KEY (REF_MEMBER_NO) REFERENCES TBL_MEMBER (NO)
    ADD CONSTRAINT TBL_ALERT_SUGGEST_NO_FK FOREIGN KEY (REF_SUGGEST_NO) REFERENCES TBL_SUGGEST (NO);
ALTER TABLE TBL_DELIVERY_STATUS
    ADD CONSTRAINT TBL_DELIVERY_STATUS_SHIPPING_TRACK_INFO_NO_FK FOREIGN KEY (REF_SHIPPING_TRACK_INFO_NO) REFERENCES TBL_SHIPPING_TRACK_INFO (NO);
ALTER TABLE TBL_PAYMENT_HISTORY
    ADD CONSTRAINT TBL_PAYMENT_HISTORY_PAYMENT_NO_FK FOREIGN KEY (REF_PAYMENT_NO) REFERENCES TBL_PAYMENT (CODE)
    ADD CONSTRAINT TBL_PAYMENT_HISTORY_SPONSORED_PRJ_NO_FK FOREIGN KEY (REF_SPONSORED_PRJ_NO) REFERENCES TBL_SPONSORED_PRJ (NO);
ALTER TABLE TBL_PERMISSION_ROLE
    ADD CONSTRAINT TBL_PERMISSION_ROLE_SELLER_ROLE_REQ_NO_FK FOREIGN KEY (REF_SELLER_ROLE_REQ_NO) REFERENCES TBL_SELLER_ROLE_REQ (NO);
ALTER TABLE TBL_PRJ
    ADD CONSTRAINT TBL_PRJ_MEMBER_NO_FK FOREIGN KEY (REF_MEMBER_NO) REFERENCES TBL_MEMBER (NO)
    ADD CONSTRAINT TBL_PRJ_CATEGORY_NO_FK FOREIGN KEY (REF_CATEGORY_NO) REFERENCES TBL_CATEGORY (NO);
ALTER TABLE TBL_PRJ_FAQ
    ADD CONSTRAINT TBL_PRJ_FAQ_PRJ_NO_FK FOREIGN KEY (REF_PRJ_NO) REFERENCES TBL_PRJ (NO);
ALTER TABLE TBL_PRJ_FILE
    ADD CONSTRAINT TBL_PRJ_FILE_PRJ_NO_FK FOREIGN KEY (REF_PRJ_NO) REFERENCES TBL_PRJ (NO);
ALTER TABLE TBL_PRJ_NEW_INFO
    ADD CONSTRAINT TBL_PRJ_NEW_INFO_MEMBER_NO_FK FOREIGN KEY (REF_MEMBER_NO) REFERENCES TBL_MEMBER (NO)
    ADD CONSTRAINT TBL_PRJ_NEW_INFO_PRJ_NO_FK FOREIGN KEY (REF_PRJ_NO) REFERENCES TBL_PRJ (NO);
-- ALTER TABLE TBL_PRJ_NEW_INFO_FILE
--     ADD CONSTRAINT TBL_PRJ_NEW_INFO_FILE_PRJ_NEW_INFO_NO_FK FOREIGN KEY (REF_PRJ_NEW_INFO_NO) REFERENCES TBL_PRJ_NEW_INFO (NO);
ALTER TABLE TBL_PRJ_PRODUCT_LIST
    ADD CONSTRAINT TBL_PRJ_PRODUCT_LIST_PRJ_NO1_FK FOREIGN KEY (REF_PRJ_NO) REFERENCES TBL_PRJ (NO)
    ADD CONSTRAINT TBL_PRJ_PRODUCT_LIST_PRODUCT_NO1_FK FOREIGN KEY (REF_PRODUCT_NO) REFERENCES TBL_PRODUCT (NO);
ALTER TABLE TBL_PRJ_PROGRESS
    ADD CONSTRAINT TBL_PRJ_PROGRESS_PRJ_NO_FK FOREIGN KEY (REF_PRJ_NO) REFERENCES TBL_PRJ (NO);
ALTER TABLE TBL_PRJ_QNA
    ADD CONSTRAINT TBL_PRJ_QNA_MEMBER_NO_FK FOREIGN KEY (REF_MEMBER_NO) REFERENCES TBL_MEMBER (NO)
    ADD CONSTRAINT TBL_PRJ_QNA_PRJ_NO_FK FOREIGN KEY (REF_PRJ_NO) REFERENCES TBL_PRJ (NO);
ALTER TABLE TBL_PRJ_QNA_ANSWER
    ADD CONSTRAINT TBL_PRJ_QNA_ANSWER_MEMBER_NO_FK FOREIGN KEY (REF_MEMBER_NO) REFERENCES TBL_MEMBER (NO)
    ADD CONSTRAINT TBL_PRJ_QNA_ANSWER_PRJ_QNA_CODE_FK FOREIGN KEY (PRJ_QNA_CODE) REFERENCES TBL_PRJ_QNA (NO);
ALTER TABLE TBL_PRJ_WISH
    ADD CONSTRAINT TBL_PRJ_WISH_MEMBER_NO_FK FOREIGN KEY (REF_MEMBER_NO) REFERENCES TBL_MEMBER (NO)
    ADD CONSTRAINT TBL_PRJ_WISH_PRJ_NO_FK FOREIGN KEY (REF_PRJ_NO) REFERENCES TBL_PRJ (NO);
ALTER TABLE TBL_REVIEW
    ADD CONSTRAINT TBL_REVIEW_MEMBER_NO_FK FOREIGN KEY (REF_MEMBER_NO) REFERENCES TBL_MEMBER (NO)
    ADD CONSTRAINT TBL_REVIEW_DELIVERY_STATUS_CODE_FK FOREIGN KEY (REF_DELIVERY_STATUS_CODE) REFERENCES TBL_DELIVERY_STATUS (NO);
ALTER TABLE TBL_ROLE_LIST
    ADD CONSTRAINT TBL_ROLE_LIST_MEMBER_NO_FK FOREIGN KEY (REF_MEMBER_NO) REFERENCES TBL_MEMBER (NO)
    ADD CONSTRAINT TBL_ROLE_LIST_MEMBER_ROLE_CODE_FK FOREIGN KEY (REF_MEMBER_ROLE_CODE) REFERENCES TBL_MEMBER_ROLE (ROLE_CODE);
ALTER TABLE TBL_SELLER_ROLE
    ADD CONSTRAINT TBL_SELLER_ROLE_MEMBER_NO_FK FOREIGN KEY (REF_MEMBER_NO) REFERENCES TBL_MEMBER (NO);
ALTER TABLE TBL_SELLER_ROLE_FILE
    ADD CONSTRAINT TBL_SELLER_ROLE_FILE_MEMBER_NO_FK FOREIGN KEY (REF_MEMBER_NO) REFERENCES TBL_MEMBER (NO);
ALTER TABLE TBL_SELLER_ROLE_REQ
    ADD CONSTRAINT TBL_SELLER_ROLE_REQ_MEMBER_NO_FK FOREIGN KEY (REF_MEMBER_NO) REFERENCES TBL_MEMBER (NO);
ALTER TABLE TBL_SHIPPING_TRACK_INFO
    ADD CONSTRAINT TBL_SHIPPING_TRACK_INFO_PAYMENT_NO_FK FOREIGN KEY (REF_PAYMENT_NO) REFERENCES TBL_PAYMENT (CODE)
    ADD CONSTRAINT TBL_SHIPPING_TRACK_INFO_MEMBER_NO_FK FOREIGN KEY (REF_MEMBER_NO) REFERENCES TBL_MEMBER (NO);
ALTER TABLE TBL_SPONSORED_PRJ
    ADD CONSTRAINT TBL_SPONSORED_PRJ_PRJ_PRODUCT_LIST_NO_FK FOREIGN KEY (REF_PRJ_PRODUCT_LIST_NO) REFERENCES TBL_PRJ_PRODUCT_LIST (NO)
    ADD CONSTRAINT TBL_SPONSORED_PRJ_MEMBER_NO_FK FOREIGN KEY (REF_MEMBER_NO) REFERENCES TBL_MEMBER (NO);
ALTER TABLE TBL_SUGGEST
    ADD CONSTRAINT TBL_SUGGEST_CATEGORY_NO_FK FOREIGN KEY (REF_CATEGORY_NO) REFERENCES TBL_CATEGORY (NO)
    ADD CONSTRAINT TBL_SUGGEST_MEMBER_NO_FK FOREIGN KEY (REF_MEMBER_NO) REFERENCES TBL_MEMBER (NO);
ALTER TABLE TBL_TERMS_HISTORY
    ADD CONSTRAINT TBL_TERMS_HISTORY_TERMS_NO_FK FOREIGN KEY (REF_TERMS_NO) REFERENCES TBL_TERMS (NO);

COMMIT;