-- 파일 정보와 해당 파일 연결된 게시물 정보 및 작성자 조회
SELECT
    F.NO AS FILE_NO,
    F.ORIGIN_NAME,
    F.CHANGE_NAME,
    F.REGIST_DATE,
    F.DELETE_YN,
    B.NO AS BOARD_NO,
    B.TITLE AS BOARD_TITLE,
    B.CONTENT AS BOARD_CONTENT,
    B.REGIST_DATE AS BOARD_REGIST_DATE,
    B.MODIFY_DATE AS BOARD_MODIFY_DATE,
    B.DELETE_YN AS BOARD_DELETE_YN,
    B.CLASSIFY_CODE AS BOARD_CLASSIFY_CODE,
    M.NO AS MEMBER_NO,
    M.NAME AS MEMBER_NAME,
    M.EMAIL AS EMAIL
FROM TBL_ADMIN_BOARD_FILE F
         JOIN TBL_ADMIN_BOARD B ON F.REF_ADMIN_BOARD_NO = B.NO
         JOIN TBL_MEMBER M ON B.NO = M.NO;

-- 특정 분류코드에 해당하는 게시물 정보 조회 : 전체조회
SELECT
    S.NO,
    S.TITLE,
    S.CONTENT,
    S.REGIST_DATE,
    S.MODIFY_DATE,
    S.CLASSIFY_CODE,
    S.REF_MEMBER_NO,
    S.DELETE_YN
FROM TBL_ADMIN_BOARD S;

-- 특정 분류코드에 해당하는 게시물 정보 조회 : A(공지사항)
SELECT
    S.NO,
    S.TITLE,
    S.CONTENT,
    S.REGIST_DATE,
    S.MODIFY_DATE,
    S.CLASSIFY_CODE,
    S.REF_MEMBER_NO,
    S.DELETE_YN
FROM TBL_ADMIN_BOARD S
WHERE S.CLASSIFY_CODE = 'A';

-- 특정 분류코드에 해당하는 게시물 정보 조회 : B(이벤트)
SELECT
    S.NO,
    S.TITLE,
    S.CONTENT,
    S.REGIST_DATE,
    S.MODIFY_DATE,
    S.CLASSIFY_CODE,
    S.REF_MEMBER_NO,
    S.DELETE_YN
FROM TBL_ADMIN_BOARD S
WHERE S.CLASSIFY_CODE = 'B';

-- 특정 분류코드에 해당하는 게시물 정보 조회 : C(보도자료)
SELECT
    S.NO,
    S.TITLE,
    S.CONTENT,
    S.REGIST_DATE,
    S.MODIFY_DATE,
    S.CLASSIFY_CODE,
    S.REF_MEMBER_NO,
    S.DELETE_YN
FROM TBL_ADMIN_BOARD S
WHERE S.CLASSIFY_CODE = 'C';